table Produccion
	lineageTag: a6738b4f-d5c5-4600-bce6-d2f158959ea6

	measure 'Cantidad producida' = SUM(Produccion[cantidad])
		formatString: #,0
		lineageTag: e6de6d9d-5ef1-4a2d-8d29-6f6daaf4ccc5

	measure 'Categorias de productos' = DISTINCTCOUNT( Produccion[ProductModelID])
		formatString: 0
		lineageTag: 88d31f3e-c47d-4fc0-845e-c5c9a1287b31

	measure 'Costo de produccion' = SUM(Produccion[CostoStandard])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 660089cf-8a7b-4d0a-a8a6-45d949a6dda2

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Locaciones de fabrica' = ```
			DISTINCTCOUNT(Produccion[LocationID]) 
			```
		formatString: 0
		lineageTag: c9c42bb9-19a6-4bc7-a0f1-33cd5dd4471c

	measure 'Productos terminados' = SUM(Produccion[almacenado])
		formatString: #,0
		lineageTag: 3c5e6c4a-a1a8-470e-9098-6c1e36fb2581

	measure 'Productos en proceso' = [Cantidad producida] - Produccion[Productos terminados]
		formatString: #,0
		lineageTag: 02698194-8731-482e-b5d1-9030917a6dfb

	measure 'Valor de produccion' = SUM(Produccion[precioLista])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 02b392fc-b3a2-4b47-ab24-ae5bf33808a0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Rentabilidad esperada' = 1-DIVIDE( [Costo de produccion], [Valor de produccion], 0)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: a954e289-8f86-4915-a85f-7103d08a7e97

	measure 'Variedad de productos' = DISTINCTCOUNT( Produccion[ProductID])
		formatString: 0
		lineageTag: 1102245a-6cc1-4b55-9342-b495a137feef

	column WorkOrderID
		dataType: string
		lineageTag: cc2d0454-b856-4edd-9260-b9451cb31816
		summarizeBy: none
		sourceColumn: WorkOrderID

		annotation SummarizationSetBy = Automatic

	column FechaInicio
		dataType: dateTime
		formatString: Long Date
		lineageTag: bd5c234a-1928-4e08-8f00-7dc9a7b72189
		summarizeBy: none
		sourceColumn: FechaInicio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FechaFin
		dataType: dateTime
		formatString: Long Date
		lineageTag: 08d3e3a3-56b2-47f8-8780-c453548c588f
		summarizeBy: none
		sourceColumn: FechaFin

		variation Variación
			isDefault
			relationship: f54183f2-b184-4fb9-88ea-4384d6c466a5
			defaultHierarchy: LocalDateTable_0e5cf930-e219-4138-b391-aff71e03b761.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FechaVencimiento
		dataType: dateTime
		formatString: Long Date
		lineageTag: b07e4d4e-524c-44b2-bdd3-f98108004f9e
		summarizeBy: none
		sourceColumn: FechaVencimiento

		variation Variación
			isDefault
			relationship: b20baa79-f46e-4fec-805b-c6598ca9ebbf
			defaultHierarchy: LocalDateTable_2abb061b-0634-4818-8e5a-d49d9243e1cd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LocationID
		dataType: string
		lineageTag: ad5359f9-e026-41b2-8452-113cb0271958
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 6255f34e-9a3e-4418-9223-db900385c7b0
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: 2ace50ef-15de-4ebc-817f-3ca6df8b7002
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column producto
		dataType: string
		lineageTag: 75a39838-e534-4b9c-b351-c34e130d983c
		summarizeBy: none
		sourceColumn: producto

		annotation SummarizationSetBy = Automatic

	column ProductModelID
		dataType: string
		lineageTag: 066ca1c4-1334-4eed-a172-3760565334e4
		summarizeBy: none
		sourceColumn: ProductModelID

		annotation SummarizationSetBy = Automatic

	column ProductModel
		dataType: string
		lineageTag: a3ac03b9-3310-41a3-9a51-2188da2a6b31
		summarizeBy: none
		sourceColumn: ProductModel

		annotation SummarizationSetBy = Automatic

	column cantidad
		dataType: int64
		formatString: 0
		lineageTag: 3a643556-26a1-48c4-b0fe-a32db0489ff3
		summarizeBy: sum
		sourceColumn: cantidad

		annotation SummarizationSetBy = Automatic

	column almacenado
		dataType: int64
		formatString: 0
		lineageTag: 4e42dbca-26ea-4f3b-8c5f-057268c9d104
		summarizeBy: sum
		sourceColumn: almacenado

		annotation SummarizationSetBy = Automatic

	column CostoStandard
		dataType: double
		lineageTag: 94403808-bc39-4d78-98f9-e252a1ee4d22
		summarizeBy: sum
		sourceColumn: CostoStandard

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precioLista
		dataType: double
		lineageTag: c3faa39d-7743-4f58-ac9c-26a133faee3a
		summarizeBy: sum
		sourceColumn: precioLista

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Produccion = m
		mode: import
		source =
				let
				    Origen = Sql.Databases(".\SQLEXPRESS"),
				    AdventureWorks2019 = Origen{[Name="AdventureWorks2019"]}[Data],
				    dbo_Produccion_PowerBI = AdventureWorks2019{[Schema="dbo",Item="Produccion_PowerBI"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_Produccion_PowerBI,{{"FechaInicio", type date}, {"FechaFin", type date}, {"FechaVencimiento", type date}, {"LocationID", type text}, {"WorkOrderID", type text}, {"ProductID", type text}, {"ProductModelID", type text}, {"CostoStandard", type number}, {"precioLista", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

