table RH
	lineageTag: e32fed81-eb41-4dac-b5df-488f30251b3a

	measure Contrataciones = COUNTROWS(RH)
		formatString: 0
		lineageTag: 63ff36c4-8922-48d0-a90d-0c6c6fab49c3

	measure 'Trabajadores activos' = CALCULATE([Contrataciones], FILTER(RH, RH[Activo] = "si"))
		formatString: 0
		lineageTag: 20bc7d20-ff3c-4680-b9aa-762cd826c8b3

	measure 'Antiguedad promedio activos' = CALCULATE(AVERAGE(RH[Antiguedad]),RH, RH[Activo] ="si")
		formatString: 0.0
		lineageTag: 2aaaff0d-2252-4e70-9715-4a92deb03701

	measure 'Antiguedad promedio retirados' = CALCULATE(AVERAGE(RH[Antiguedad]),RH, RH[Activo] ="no")
		formatString: 0.0
		lineageTag: 569de7f1-5527-4fe2-b856-92ab9c88741f

	measure 'Trabajadores retirados' = CALCULATE([Contrataciones], FILTER(RH, RH[Activo] = "no"))
		formatString: 0
		lineageTag: 3bed0cbd-f961-433d-868d-cc9d1767e25d

	measure 'Total acumulado de Contrataciones en fechaContrato' =
			
			CALCULATE(
				[Contrataciones],
				FILTER(
					ALLSELECTED('RH'[fechaContrato]),
					ISONORAFTER('RH'[fechaContrato], MAX('RH'[fechaContrato]), DESC)
				)
			)
		formatString: 0
		lineageTag: 6c6be6e9-87b2-4039-bd95-82bf530af416

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "RunningTotal"
				}

		changedProperty = FormatString

	measure 'Rotacion de personal' = [Trabajadores retirados] / (([Contrataciones]+[Total acumulado de Contrataciones en fechaContrato])/2)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3575f005-19e1-430d-aa84-a8b1774208f3

	column BusinessEntityID
		dataType: string
		lineageTag: 8bd25172-f03c-434b-833f-52f9c49f0455
		summarizeBy: none
		sourceColumn: BusinessEntityID

		annotation SummarizationSetBy = Automatic

	column fechaContrato
		dataType: dateTime
		formatString: Long Date
		lineageTag: a25cd09a-a02f-4dc9-824f-596b42c7e31d
		summarizeBy: none
		sourceColumn: fechaContrato

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column finContrato
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0dcfa07a-0820-4f9b-9365-246ccedecc76
		summarizeBy: none
		sourceColumn: finContrato

		variation Variación
			isDefault
			relationship: d0b80f72-29a4-49d8-8170-ac6855b6f179
			defaultHierarchy: LocalDateTable_4c3a2388-bdc9-4f31-a7fa-d6b9001af1a1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Gerencia
		dataType: string
		lineageTag: d783c7b6-1cc3-4ba5-98c7-d1baf77b0646
		summarizeBy: none
		sourceColumn: Gerencia

		annotation SummarizationSetBy = Automatic

	column Departamento
		dataType: string
		lineageTag: 194cb5b1-6dad-49d0-b491-cfc943ca4eb9
		summarizeBy: none
		sourceColumn: Departamento

		annotation SummarizationSetBy = Automatic

	column Empleado
		dataType: string
		lineageTag: cdbfeeab-2f1e-4534-bdae-d82954d1e4f2
		summarizeBy: none
		sourceColumn: Empleado

		annotation SummarizationSetBy = Automatic

	column Cargo
		dataType: string
		lineageTag: 5aa29eb3-76d7-411f-8878-8538df84182a
		summarizeBy: none
		sourceColumn: Cargo

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: d85161e8-b26e-4462-a4ee-e6b6559efea0
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 11c005bf-1e59-41f0-a851-4ce4fa0cabf4
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b930eca4-19d0-45b9-989a-30ddee3a52df
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variación
			isDefault
			relationship: 8151d411-f63c-41b3-a92f-5bb2bd4032d2
			defaultHierarchy: LocalDateTable_e43a2367-44c4-4d8d-9f80-91282322cf55.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Activo
		dataType: string
		lineageTag: a66957ea-2716-4394-8c4a-6192853027b1
		summarizeBy: none
		sourceColumn: Activo

		annotation SummarizationSetBy = Automatic

	column Genero
		dataType: string
		lineageTag: 2036ae6c-1ecf-4fa9-80fb-663ad4facd75
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	column Edad
		dataType: double
		lineageTag: f91c4e67-7844-4aac-bc13-6bb8654fdf22
		summarizeBy: sum
		sourceColumn: Edad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Antiguedad
		dataType: double
		lineageTag: c4d7dcb4-cf04-4881-a608-0c528dc3ab37
		summarizeBy: sum
		sourceColumn: Antiguedad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Grupo etario' = ```
			SWITCH( TRUE(),
			RH[Edad] <=30, "30 o menos",
			RH[Edad] <=40, "31-40",
			RH[Edad] <=50, "41-50",
			RH[Edad] <=60, "51-60",
			RH[Edad] >60, "60 o más")
			
			
			```
		lineageTag: 01936e53-87fd-4939-bcce-7cf04014f2cb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition RH = m
		mode: import
		source = ```
				let
				    Origen = Sql.Databases(".\SQLEXPRESS"),
				    AdventureWorks2019 = Origen{[Name="AdventureWorks2019"]}[Data],
				    dbo_RH_PowerBI = AdventureWorks2019{[Schema="dbo",Item="RH_PowerBI"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_RH_PowerBI,{{"BusinessEntityID", type text}, {"fechaContrato", type date}, {"finContrato", type date}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"NombreEmpleado", "Empleado"}, {"JobTitle", "Cargo"}}),
				    #"Columna Activo" = Table.AddColumn(#"Columnas con nombre cambiado", "Actico", each if [finContrato] = null then "si" else "no"),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columna Activo",{{"Actico", "Activo"}}),
				    #"Columna Genero" = Table.AddColumn(#"Columnas con nombre cambiado1", "Genero", each if [Gender] = "M" then "Masculino" else if [Gender] = "F" then "Femenino" else "Otro"),
				    #"Columna Edad" = Table.AddColumn(#"Columna Genero", "Edad", each (Duration.Days(Duration.From(Date.From(DateTime.LocalNow())-[BirthDate]))/30)/12),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columna Edad",{{"Edad", type number}}),
				    #"Columna Antiguedad" = Table.AddColumn(#"Tipo cambiado1", "Antiguedad", each if [Activo] = "si" then 
				(Duration.Days(Duration.From(Date.From(DateTime.LocalNow())
				- [fechaContrato]))/30
				)/12 
				else (Duration.Days(Duration.From([finContrato] - [fechaContrato]))/30)/12),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columna Antiguedad",{{"Antiguedad", type number}})
				in
				    #"Tipo cambiado2"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

